version: "3"
services:
  demo-app:
    build:
      context: demo-app
      dockerfile: Dockerfile
    ports:
      - ${SPRINGBOOT_PORT}:8080
    # websites:
    #   image: nginx:alpine
    #   volumes:
    #     - ./frontend-trial:/usr/share/nginx/html
    #   ports:
    #     - 5002:80
    #   depends_on:
    #     - demo-app
  react-app:
    build:
      context: my-app
      dockerfile: Dockerfile
      args:
        REACT_APP_SPRINGBOOT_PORT: ${SPRINGBOOT_PORT}
    ports:
      - ${REACT_PORT}:80
